[build]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh"
  publish = "_site"
  environment = { PHP_VERSION = "7.2", CECIL_VERSION = "4.19.2", RUBY_VERSION = "2.6.2" }

[context.deploy-preview]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x .netlify/build.sh && bash .netlify/build.sh $DEPLOY_PRIME_URL"

[template.environment]
  CECIL_SITE_TITLE = "Blog's title"
  CECIL_SITE_BASELINE = "Short description (~ 20 characters)"
  CECIL_SITE_DESCRIPTION = "Full description (~ 250 characters)"
